# Disable default CI trigger. Otherwise, runs on every push to every branch.
# Ref: https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git#opting-out-of-ci
trigger: none

# Name builds with the definition name, date, and build-count-for-that-day. For
# example, "PF.PR_20210214.1".
# Refs:
# - https://docs.microsoft.com/en-us/azure/devops/pipelines/process/run-number
# - https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables
name: $(Build.DefinitionName)_$(date:yyMM).$(date:dd)$(rev:rrr)

jobs:
  ####################
  # Visual Studio 2017
  ####################

  - job: Win32Vs17Build
    displayName: PF Win32 VS2017 Build
    pool:
      name: xbl-1es-vs2017-pool
    timeoutInMinutes: 180
    strategy:
      matrix:
        x86_Release:
          Platform: x86
          Configuration: Release
          prefast: Disable
    steps:
      - template: Tasks/vs2017-build.yml
        parameters:
          platform: $(Platform)
          configuration: $(Configuration)
          prefast: Disable

  # # ####################
  # # # Unit Tests
  # # ####################

  # - job: UnitTestBuild
  #   displayName: PF Unit Tests
  #   pool:
  #     name: xbl-1es-vs2017
  #   timeoutInMinutes: 180
  #   strategy:
  #     matrix:
  #       x64_Debug:
  #         Platform: x64
  #         Configuration: Debug
  #   steps:
  #     - template: Tasks/unittest-build.yml
  #       parameters:
  #         platform: $(Platform)
  #         configuration: $(Configuration)

  # ####################
  # # Visual Studio 2019
  # ####################

  # - job: Win32Vs19Build
  #   displayName: PF Win32 VS2019 Build
  #   pool:
  #     name: xbl-1es-vs2019-pool
  #   timeoutInMinutes: 180
  #   strategy:
  #     matrix:
  #       x86_Debug:
  #         Platform: x86
  #         Configuration: Debug
  #         prefast: Disable
  #       x64_Release:
  #         Platform: x64
  #         Configuration: Release
  #         prefast: Disable
  #   steps:
  #     - template: Tasks/vs2019-build.yml
  #       parameters:
  #         platform: $(Platform)
  #         configuration: $(Configuration)
  #         prefast: Disable

  ####################
  # GDK VS2017
  ####################

  - job: GDKBuildVS2017
    displayName: PF GDK VS2017 Build    
    pool:
      name: xbl-1es-vs2017-pool
    timeoutInMinutes: 180
    strategy:
      matrix:
        Gaming_Desktop_x64_Release:
          Platform: Gaming.Desktop.x64
          Configuration: Release
    steps:
      - template: Tasks/gdk-vs2017-build.yml
        parameters:
          platform: $(Platform)
          configuration: $(Configuration)
          publishArtifacts: false
          
  # ####################
  # # GDK VS2019
  # ####################

  # - job: GDKBuildVS2019
  #   displayName: PF GDK VS2019 Build
  #   pool:
  #     name: xbl-1es-vs2019-pool
  #   timeoutInMinutes: 180
  #   strategy:
  #     matrix:
  #       Gaming_Desktop_x64_Debug:
  #         Platform: Gaming.Desktop.x64
  #         Configuration: Debug
  #   steps:
  #     - template: Tasks/gdk-vs2019-build.yml
  #       parameters:
  #         platform: $(Platform)
  #         configuration: $(Configuration)
  #         publishArtifacts: false

  #########################
  # Send email on failure
  #########################

  - job: SendEmailOnFailure
    displayName: Send email on build failure
    condition: and(failed(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    dependsOn:
      - Win32Vs17Build
      #- Win32Vs19Build
      - GDKBuildVS2017
      #- GDKBuildVS2019
      #- UnitTestBuild
    pool:
      name: xbl-1es-vs2019-pool
    steps:
      # Send an email to the team.
      - template: Tasks/send-build-failed-email.yml
        parameters:
          toAddress: $(Build.RequestedForEmail)

